### PR TITLE
fix Item dupe

### PR DESCRIPTION
**Pull request by yukieiji**
Disabled retrieval of TileEntity with inventory.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5022

### CODE REVIEW

**Comment by Prometheus0000** [comment]
Does this mean it's safe to use them now?

**Comment by yukieiji** [comment]
I tested a few things, and it works fine, no dupe..
However, retrieval of TileEntity having inventory is no longer working.

**Comment by boubou19** [comment]
omg i love you so much!

**Comment by bartimaeusnek** [comment]
> 
> 
> Does this mean it's safe to use them now?

Not really, only if the TileEntity uses no *proper* coded inventory. Will break if the TE uses a custom implementation.

**Comment by yukieiji** [comment]
@bartimaeusnek How do I change it so it doesn't break?
Should I get the inventory size to be judged?

**Pull request merged**
